// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5zzlo-pqdmsG-4fQWCW-pFOtZKN5hHQ',
    appId: '1:361640418654:web:1a3edf6764a4a43bf103cf',
    messagingSenderId: '361640418654',
    projectId: 'spotify-b42e5',
    authDomain: 'spotify-b42e5.firebaseapp.com',
    storageBucket: 'spotify-b42e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuWccwiLujy3hHg_vaAX2DZiDirLlwOHA',
    appId: '1:361640418654:android:c2e345b7525d6540f103cf',
    messagingSenderId: '361640418654',
    projectId: 'spotify-b42e5',
    storageBucket: 'spotify-b42e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx9VTrBxXfq5VB2Z2gFQ1BSLBMhycPq1E',
    appId: '1:361640418654:ios:616c799bbb501813f103cf',
    messagingSenderId: '361640418654',
    projectId: 'spotify-b42e5',
    storageBucket: 'spotify-b42e5.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx9VTrBxXfq5VB2Z2gFQ1BSLBMhycPq1E',
    appId: '1:361640418654:ios:616c799bbb501813f103cf',
    messagingSenderId: '361640418654',
    projectId: 'spotify-b42e5',
    storageBucket: 'spotify-b42e5.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5zzlo-pqdmsG-4fQWCW-pFOtZKN5hHQ',
    appId: '1:361640418654:web:33e68ec696946a12f103cf',
    messagingSenderId: '361640418654',
    projectId: 'spotify-b42e5',
    authDomain: 'spotify-b42e5.firebaseapp.com',
    storageBucket: 'spotify-b42e5.firebasestorage.app',
  );
}
